### ISSUE TITLE
Request: Also support Quarm

### ISSUE THREAD

**Issue by docfunfrock** [nickgal/EQMacDocker#1]
[Project Quarm](https://github.com/SecretsOTheP/EQMacEmu) has forks of the `Quests` and `Server` submodules for their upcoming server launch.  It would be super cool if your Docker wrapper could support both TAKP and Quarm since they share the overwhelming majority of their code.  It wouldn't need to be anything fancy, maybe just a different branch with different submodule URLs.

I can try to open a PR in the coming days if that's something you would be interested in.

**Comment by nickgal** [comment]
Added a [branch](https://github.com/nickgal/EQMacDocker/tree/quarm). 

Let me know how it works, there were some migration state issues I tried to address.
